# Generated by Django 5.2 on 2025-04-09 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='agendada', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
