# Generated by Django 5.2 on 2025-04-10 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_consulta_tipo_consulta_atualizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='participantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo'), ('avaliacao', 'Avaliação'), ('retorno', 'Retorno')], default='individual', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('profissional', 'data', 'hora')},
        ),
    ]
