# Generated by Django 5.2 on 2025-04-19 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profissional',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Selecione', 'Selecione'), ('CLT', 'CLT'), ('PJ', 'PJ'), ('Autônomo', 'Autônomo')], default='Selecione', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='conselho',
            field=models.CharField(choices=[('Selecione', 'Selecione'), ('CRM', 'CRM'), ('COREN', 'COREN'), ('CRP', 'CRP'), ('CREFITO', 'CREFITO'), ('CRN', 'CRN'), ('CRF', 'CRF'), ('CRO', 'CRO'), ('CREFONO', 'CREFONO'), ('CRBM', 'CRBM'), ('CRMV', 'CRMV'), ('CREF', 'CREF')], default='Selecione', max_length=20),
        ),
        migrations.AddField(
            model_name='profissional',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profissional',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='numero_conselho',
            field=models.CharField(default='000000-SP', max_length=20),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
