# Generated by Django 5.2 on 2025-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_profissional_atualizado_em_profissional_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='categoria',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('Autônomo', 'Autônomo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='conselho',
            field=models.CharField(choices=[('', 'Selecione'), ('CRM', 'CRM'), ('COREN', 'COREN'), ('CRP', 'CRP'), ('CREFITO', 'CREFITO'), ('CRN', 'CRN'), ('CRF', 'CRF'), ('CRO', 'CRO'), ('CREFONO', 'CREFONO'), ('CRBM', 'CRBM'), ('CRMV', 'CRMV'), ('CREF', 'CREF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='numero_conselho',
            field=models.CharField(max_length=20),
        ),
    ]
