# Generated by Django 5.2 on 2025-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('mensagem', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('agendada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
