# Generated by Django 5.2 on 2025-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='profissional',
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_convenio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_convenio',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('Particular', 'Particular'), ('Plano de Saude', 'Plano de Saúde'), ('SUS', 'SUS'), ('Popular', 'Popular'), ('Parcerias', 'Parcerias'), ('Filantrópico', 'Filantrópico'), ('Domiciliar', 'Domiciliar'), ('Online/Telemedicina', 'Online/Telemedicina')], default='', max_length=50),
        ),
    ]
